# ---------------------------------------------------------------------------
# AIUC-1 SOC 2 Compliance Lab — Disclosure Injector
# ---------------------------------------------------------------------------
# Injects the mandatory AI disclosure footer into every function response
# at the infrastructure layer.  The LLM does not need to remember to add
# the footer — the enforcement layer guarantees it.
#
# This is a direct implementation of AIUC-1 E016:
#   "Implement clear disclosure mechanisms to inform users when they are
#    interacting with AI systems rather than humans."
#
# The disclosure is injected into the response envelope's data section
# as a structured field, not appended as free text.  This makes it
# machine-readable and impossible to accidentally omit.
#
# AIUC-1 Controls:
#   E016  Implement AI disclosure mechanisms
#   E017  Document system transparency policy
# ---------------------------------------------------------------------------

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger("aiuc1.enforcement.disclosure")

# The canonical disclosure text — defined once, used everywhere
_DISCLOSURE_TEXT = (
    "This output was generated by the AIUC-1 SOC 2 Learning Agent, "
    "an AI system built on Azure AI Foundry.  All data has been processed "
    "through the AIUC-1 enforcement layer, which applies mandatory "
    "sanitisation, scope boundary enforcement, and audit logging.  "
    "This assessment should be reviewed by a qualified human auditor."
)

_DISCLOSURE_SHORT = (
    "AI-generated output.  Enforcement layer applied.  "
    "Human review recommended."
)


class DisclosureInjector:
    """Injects AI disclosure metadata into function responses.

    The injector adds a structured `ai_disclosure` field to every
    response envelope.  This field contains:

    - The disclosure text (E016)
    - The enforcement layer version
    - A timestamp of when disclosure was injected
    - The list of AIUC-1 controls enforced on this response

    Because the disclosure is a structured field (not free text), it
    cannot be accidentally stripped by downstream processing.
    """

    VERSION = "1.0.0"

    def __init__(self, custom_text: str | None = None) -> None:
        self._text = custom_text or _DISCLOSURE_TEXT
        self._short = _DISCLOSURE_SHORT
        self._injection_count = 0

    def inject(
        self,
        envelope: dict[str, Any],
        function_name: str,
        enforced_controls: list[str] | None = None,
    ) -> dict[str, Any]:
        """Inject AI disclosure into a response envelope.

        Args:
            envelope: The function response envelope.
            function_name: Name of the function that produced the response.
            enforced_controls: List of AIUC-1 control IDs enforced.

        Returns:
            The envelope with the ai_disclosure field added.
        """
        self._injection_count += 1

        disclosure = {
            "ai_generated": True,
            "disclosure_text": self._text,
            "disclosure_short": self._short,
            "enforcement_layer_version": self.VERSION,
            "function_name": function_name,
            "enforced_controls": enforced_controls or [],
            "injected_at": datetime.now(timezone.utc).isoformat(),
            "aiuc1_control": "E016",
            "note": (
                "This disclosure was injected by the enforcement layer "
                "(architectural).  It cannot be suppressed by the LLM."
            ),
        }

        envelope["ai_disclosure"] = disclosure
        return envelope

    @property
    def injection_count(self) -> int:
        """Total number of disclosures injected."""
        return self._injection_count

    @staticmethod
    def get_disclosure_text() -> str:
        """Return the canonical disclosure text for external use."""
        return _DISCLOSURE_TEXT
