# ---------------------------------------------------------------------------
# AIUC-1 SOC 2 Compliance Lab — run_terraform_apply
# ---------------------------------------------------------------------------
# Action Function (3 of 4)
#
# Purpose:
#   Executes `terraform apply` ONLY if a valid approval token from
#   run_terraform_plan is provided.  This is the enforcement point for
#   AIUC-1-11 (Human Oversight) — no infrastructure changes happen
#   without an approved plan.
#
# Security model:
#   1. Caller must provide the plan_hash and approval_token from
#      run_terraform_plan
#   2. The token is validated via HMAC — it cannot be forged
#   3. The plan_hash ensures the exact same plan is being applied
#      (no plan drift between plan and apply)
#   4. A security event is logged regardless of outcome
#
# AIUC-1 Controls:
#   AIUC-1-11  Human Oversight     — approval token required
#   AIUC-1-18  Input Validation    — validates token and hash
#   AIUC-1-19  Output Filtering    — sanitises apply output
#   AIUC-1-22  Logging             — logs apply execution
#   AIUC-1-30  Change Management   — terraform apply is a controlled change
#   AIUC-1-34  Credential Mgmt    — uses env-based auth, no hardcoded creds
# ---------------------------------------------------------------------------

import azure.functions as func
import logging
import json
import hashlib
import hmac
import subprocess
import os
from datetime import datetime, timezone

import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from shared.config import get_settings
from shared.logger import log_event, log_function_call
from shared.response import build_success_response, build_error_response
from shared.sanitizer import redact_secrets

app = func.FunctionApp(http_auth_level=func.AuthLevel.FUNCTION)

logger = logging.getLogger("aiuc1.run_terraform_apply")


def _validate_approval_token(plan_hash: str, token: str) -> bool:
    """Validate the HMAC approval token against the plan hash.

    Returns True if the token is valid (i.e., it was generated by
    run_terraform_plan for this exact plan hash).
    """
    secret = os.environ.get("TERRAFORM_APPROVAL_SECRET", "lab-default-secret")
    expected = hmac.new(
        secret.encode(),
        plan_hash.encode(),
        hashlib.sha256,
    ).hexdigest()
    return hmac.compare_digest(token, expected)


@app.route(route="run_terraform_apply", methods=["POST"])
@log_function_call("run_terraform_apply", aiuc1_controls=["AIUC-1-11", "AIUC-1-18", "AIUC-1-19", "AIUC-1-22", "AIUC-1-30", "AIUC-1-34"])
def main(req: func.HttpRequest) -> func.HttpResponse:
    """Execute terraform apply with approval token validation.

    Request body (JSON):
        {
            "plan_hash": "abc123...",        // required — from run_terraform_plan
            "approval_token": "def456...",   // required — from run_terraform_plan
            "working_dir": "terraform/...",  // optional — override default
            "target": "module.nsg_fix",      // optional — specific target
            "agent_id": "iac-deployer"       // optional — for audit trail
        }

    Response:
        Standard envelope with apply results.
    """
    try:
        body = req.get_json()
    except ValueError:
        return build_error_response(
            "run_terraform_apply",
            "Request body must be valid JSON",
            error_code="INVALID_JSON",
            status_code=400,
        )

    # ---- Input validation (AIUC-1-18) ------------------------------------
    plan_hash = body.get("plan_hash", "").strip()
    approval_token = body.get("approval_token", "").strip()
    agent_id = body.get("agent_id", "unknown")

    if not plan_hash or not approval_token:
        log_event(
            "security_event",
            function_name="run_terraform_apply",
            agent_id=agent_id,
            severity="WARNING",
            details={"reason": "Missing plan_hash or approval_token"},
            aiuc1_controls=["AIUC-1-11"],
        )
        return build_error_response(
            "run_terraform_apply",
            "Both plan_hash and approval_token are required. "
            "Run run_terraform_plan first to obtain these values.",
            error_code="MISSING_APPROVAL",
            status_code=400,
        )

    # ---- Validate approval token (AIUC-1-11) -----------------------------
    if not _validate_approval_token(plan_hash, approval_token):
        log_event(
            "security_event",
            function_name="run_terraform_apply",
            agent_id=agent_id,
            severity="ERROR",
            details={
                "reason": "Invalid approval token",
                "plan_hash_prefix": plan_hash[:8],
            },
            aiuc1_controls=["AIUC-1-11"],
        )
        return build_error_response(
            "run_terraform_apply",
            "Invalid approval token. The plan may have changed since approval. "
            "Re-run run_terraform_plan to get a fresh token.",
            error_code="INVALID_APPROVAL_TOKEN",
            status_code=403,
        )

    # ---- Determine working directory -------------------------------------
    settings = get_settings()
    working_dir = body.get("working_dir", settings.terraform_working_dir)
    if not working_dir:
        working_dir = os.path.join(settings.git_repo_path, "terraform")

    if not os.path.isdir(working_dir):
        return build_error_response(
            "run_terraform_apply",
            f"Terraform working directory does not exist: {working_dir}",
            error_code="INVALID_WORKING_DIR",
            status_code=400,
        )

    # ---- Build terraform apply command -----------------------------------
    cmd = ["terraform", "apply", "-auto-approve", "-no-color"]

    target = body.get("target")
    if target:
        cmd.extend(["-target", target])

    # ---- Execute terraform apply -----------------------------------------
    log_event(
        "terraform_apply_start",
        function_name="run_terraform_apply",
        agent_id=agent_id,
        details={
            "working_dir": working_dir,
            "plan_hash_prefix": plan_hash[:8],
            "target": target,
        },
        aiuc1_controls=["AIUC-1-30"],
    )

    try:
        apply_result = subprocess.run(
            cmd,
            cwd=working_dir,
            capture_output=True,
            text=True,
            timeout=600,  # 10-minute timeout for apply
        )

        apply_output = apply_result.stdout
        apply_stderr = apply_result.stderr
        success = apply_result.returncode == 0

        if not success:
            log_event(
                "terraform_apply_failed",
                function_name="run_terraform_apply",
                agent_id=agent_id,
                severity="ERROR",
                details={
                    "exit_code": apply_result.returncode,
                    "stderr_preview": redact_secrets(apply_stderr[:500]),
                },
                aiuc1_controls=["AIUC-1-22", "AIUC-1-30"],
            )
            return build_error_response(
                "run_terraform_apply",
                redact_secrets(apply_stderr or apply_output),
                error_code="TERRAFORM_APPLY_ERROR",
                status_code=500,
                details={"exit_code": apply_result.returncode},
            )

    except subprocess.TimeoutExpired:
        return build_error_response(
            "run_terraform_apply",
            "Terraform apply timed out after 600 seconds",
            error_code="TIMEOUT",
            status_code=504,
        )
    except FileNotFoundError:
        return build_error_response(
            "run_terraform_apply",
            "Terraform binary not found",
            error_code="TERRAFORM_NOT_FOUND",
            status_code=500,
        )

    # ---- Log successful apply --------------------------------------------
    log_event(
        "terraform_apply_success",
        function_name="run_terraform_apply",
        agent_id=agent_id,
        details={
            "plan_hash_prefix": plan_hash[:8],
            "output_length": len(apply_output),
        },
        aiuc1_controls=["AIUC-1-22", "AIUC-1-30"],
    )

    result = {
        "success": True,
        "plan_hash": plan_hash,
        "apply_summary": redact_secrets(apply_output[:5000]),
        "working_dir": working_dir,
        "target": target,
        "applied_by_agent": agent_id,
        "applied_at": datetime.now(timezone.utc).isoformat(),
        "change_management_note": (
            "This apply was executed with a validated approval token. "
            "The plan hash ensures the exact approved plan was applied. "
            "Full output is logged in Application Insights for audit."
        ),
    }

    return build_success_response(
        "run_terraform_apply",
        result,
        aiuc1_controls=["AIUC-1-11", "AIUC-1-18", "AIUC-1-19", "AIUC-1-22", "AIUC-1-30", "AIUC-1-34"],
    )
